version: '3'
services:
  jamovi-deps:
    image: jamovi/jamovi-deps:2.5.0
    build:
      context: .
      dockerfile: docker/deps-Dockerfile
    profiles:
      - donotstart

  # vite:
  #   image: jonathonlove/vite:1.0
  #   container_name: vite
  #   privileged: true
  #   command: [ 'mkdir -p /source/merged && unionfs-fuse -o cow /source/server:/source/client=RW /source/merged && cd /source/merged && echo installing npm deps && npm install && echo starting vite server && vite --host' ]
  #   volumes:
  #     - './client/main:/source/client/main'
  #     - './client/resultsview:/source/client/resultsview'
  #     - './client/analysisui:/source/client/analysisui'
  #     - './client/lib:/source/client/lib'
  #     - './client/assets:/source/client/assets'
  #     - './client/common:/source/client/common'
  #     - './client/index.html:/source/client/index.html'
  #     - './client/resultsview.html:/source/client/resultsview.html'
  #     - './client/analysisui.html:/source/client/analysisui.html'
  #     - './client/tsconfig.json:/source/client/tsconfig.json'
  #     - './client/vite.config.ts:/source/client/vite.config.ts'
  #     - './client/package.json:/source/client/package.json'
  #     - './server/jamovi/server/jamovi.proto:/source/server/assets/coms.proto'
  #   ports:
  #     - '5173:5173'
  #     - '24678:24678'

  tests:
    image: jamovi/jamovi:2.5.0
    build:
      context: .
      dockerfile: docker/jamovi-Dockerfile
    platform: linux/amd64
    profiles:
      - donotstart
    command: ["/usr/bin/python3 -m pytest /usr/lib/jamovi/server"]

  jamovi:
    image: jamovi/jamovi:2.5.0
    container_name: jamovi
    build:
      context: .
      dockerfile: docker/jamovi-Dockerfile
    platform: linux/amd64
    ports:
      - '41337:41337'
      - '41338:41338'
      - '41339:41339'
    command: ["/usr/bin/python3 -m jamovi.server 41337 --if=*"]
    stdin_open: true
    environment:

        # for development, use the vite dev server
        # (uncomment/enable the vite service above too)
        # JAMOVI_DEV_SERVER: "http://vite:5173"

        # block Rj - don't enable unless you understand the risks!
        JAMOVI_ALLOW_ARBITRARY_CODE: 'false'

        # for security, jamovi runs across 3 origins
        #
        # # separate by port
        JAMOVI_HOST_A: '127.0.0.1:41337'
        JAMOVI_HOST_B: '127.0.0.1:41338'
        JAMOVI_HOST_C: '127.0.0.1:41339'

        # separate by host (RECOMMENDED)
        # JAMOVI_HOST_A: 'jamovi.127.0.0.1.nip.io:41337'
        # JAMOVI_HOST_B: 'a.jamovi.127.0.0.1.nip.io:41337'
        # JAMOVI_HOST_C: 'r.jamovi.127.0.0.1.nip.io:41337'

        # separate by path (NOT RECOMMENDED! REDUCES SECURITY!)
        # JAMOVI_HOST_A: 'jamovi.127.0.0.1.nip.io:41337'
        # JAMOVI_HOST_B: 'jamovi.127.0.0.1.nip.io:41337/analyses'
        # JAMOVI_HOST_C: 'jamovi.127.0.0.1.nip.io:41337/results'

        # prevent unauthorized access
        # JAMOVI_ACCESS_KEY: 'yourpasswordhere'
        # then access jamovi with ?access_key=yourpasswordhere added to the url
        # i.e. 127.0.0.1:41337/?access_key=yourpasswordhere
        # or alternatively, remove the password requirement:
        # JAMOVI_ACCESS_KEY: ''

    volumes:
      - $HOME/Documents:/root/Documents
