
# This file is automatically generated, you probably don't want to edit this

openSesameOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "openSesameOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            alt = "notequal",
            varEq = TRUE,
            open = FALSE,
            file = NULL, ...) {

            super$initialize(
                package="opensesame",
                name="openSesame",
                requiresData=FALSE,
                ...)

            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "notequal",
                    "onegreater",
                    "twogreater"),
                default="notequal")
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)
            private$..open <- jmvcore::OptionAction$new(
                "open",
                open,
                action="open")
            private$..file <- jmvcore::OptionFile$new(
                "file",
                file,
                multi=FALSE)

            self$.addOption(private$..alt)
            self$.addOption(private$..varEq)
            self$.addOption(private$..open)
            self$.addOption(private$..file)
        }),
    active = list(
        alt = function() private$..alt$value,
        varEq = function() private$..varEq$value,
        open = function() private$..open$value,
        file = function() private$..file$value),
    private = list(
        ..alt = NA,
        ..varEq = NA,
        ..open = NA,
        ..file = NA)
)

openSesameResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "openSesameResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="openSesame")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="openSesame"))}))

openSesameBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "openSesameBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "opensesame",
                name = "openSesame",
                version = c(1,0,0),
                options = options,
                results = openSesameResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' openSesame
#'
#'
#' @param alt .
#' @param varEq .
#' @param open .
#' @param file .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
openSesame <- function(
    alt = "notequal",
    varEq = TRUE,
    open = FALSE,
    file) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("openSesame requires jmvcore to be installed (restart may be required)")


    options <- openSesameOptions$new(
        alt = alt,
        varEq = varEq,
        open = open,
        file = file)

    analysis <- openSesameClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

