
# This file is automatically generated, you probably don't want to edit this

# This object is here to simplify Roxygen compilation

#' jamovi classes
#'
#' jamovi classes exported for jamovi to access (see https://www.jamovi.org)
jamovi <- NULL
