
const included = [

    // base

    'R',
    'base',
    'compiler',
    'datasets',
    'graphics',
    'grDevices',
    'grid',
    'methods',
    'parallel',
    'splines',
    'stats',
    'stats4',
    'tcltk',
    'utils',
    'tools',

    // recommended

    'KernSmooth',
    'MASS',
    'Matrix',
    'boot',
    'class',
    'cluster',
    'codetools',
    'foreign',
    'lattice',
    'mgcv',
    'nlme',
    'nnet',
    'rpart',
    'spatial',
    'survival',
];

const R402base = included.concat([
    'jmvcore',
    'R6',
    'RColorBrewer',
    'base64enc',
    'bitops',
    'curl',
    'fansi',
    'farver',
    'highr',
    'labeling',
    'magrittr',
    'praise',
    'prettyunits',
    'rlang',
    'rstudioapi',
    'systemfonts',
    'utf8',
    'viridisLite',
    'yaml',
    'RCurl',
    'Rcpp',
    'assertthat',
    'backports',
    'colorspace',
    'crayon',
    'digest',
    'ellipsis',
    'evaluate',
    'glue',
    'gtable',
    'jsonlite',
    'mime',
    'pkgconfig',
    'ps',
    'ragg',
    'remotes',
    'stringi',
    'withr',
    'xfun',
    'RInside',
    'RProtoBuf',
    'cli',
    'htmltools',
    'lifecycle',
    'markdown',
    'munsell',
    'processx',
    'rprojroot',
    'stringr',
    'tinytex',
    'vctrs',
    'callr',
    'desc',
    'knitr',
    'pillar',
    'scales',
    'pkgbuild',
    'rmarkdown',
    'tibble',
    'pkgload',
    'testthat',
    'isoband',
    'ggplot2',
]);

const R402jmv = R402base.concat([
    'GPArotation',
    'RcppParallel',
    'ca',
    'carData',
    'contfrac',
    'cpp11',
    'glasso',
    'jpeg',
    'lisrelToR',
    'matrixStats',
    'matrixcalc',
    'nloptr',
    'numDeriv',
    'pbivnorm',
    'png',
    'polyclip',
    'qvcalc',
    'rematch',
    'rjson',
    'tmvnsim',
    'truncnorm',
    'whisker',
    'zip',
    'Formula',
    'MatrixModels',
    'PMCMR',
    'RUnit',
    'RcppArmadillo',
    'RcppEigen',
    'Rsolnp',
    'SparseM',
    'TH.data',
    'XML',
    'abind',
    'caTools',
    'cellranger',
    'checkmate',
    'clipr',
    'coda',
    'corpcor',
    'data.table',
    'deSolve',
    'elliptic',
    'estimability',
    'fdrtool',
    'forcats',
    'generics',
    'ggrepel',
    'gridExtra',
    'gtools',
    'hms',
    'htmlwidgets',
    'igraph',
    'latticeExtra',
    'minqa',
    'mnormt',
    'mvnormtest',
    'mvtnorm',
    'openxlsx',
    'pbapply',
    'plyr',
    'purrr',
    'relimp',
    'sp',
    'ssanv',
    'statmod',
    'tweenr',
    'xtable',
    'zoo',
    'BDgraph',
    'StanHeaders',
    'conquer',
    'd3Network',
    'emmeans',
    'exactci',
    'gdata',
    'ggridges',
    'gnm',
    'graphlayouts',
    'htmlTable',
    'huge',
    'hypergeo',
    'kutils',
    'lavaan',
    'lme4',
    'lmtest',
    'maptools',
    'progress',
    'psych',
    'readr',
    'reshape',
    'reshape2',
    'rpf',
    'sandwich',
    'tidyselect',
    'viridis',
    'BayesFactor',
    'GGally',
    'Hmisc',
    'OpenMx',
    'dplyr',
    'exact2x2',
    'ggforce',
    'gplots',
    'haven',
    'lmerTest',
    'multcomp',
    'pbkrtest',
    'quantreg',
    'readxl',
    'regsem',
    'rockchalk',
    'vcd',
    'ROCR',
    'arm',
    'rio',
    'tidyr',
    'vcdExtra',
    'car',
    'mi',
    'tidygraph',
    'afex',
    'ggraph',
    'sem',
    'qgraph',
    'semPlot',
]);

const R405base = included.concat([
    'jmvcore',
    'R6',
    'RColorBrewer',
    'base64enc',
    'bitops',
    'brio',
    'cpp11',
    'curl',
    'fansi',
    'farver',
    'highr',
    'magrittr',
    'praise',
    'prettyunits',
    'rprojroot',
    'rstudioapi',
    'utf8',
    'viridisLite',
    'yaml',
    'RCurl',
    'Rcpp',
    'assertthat',
    'colorspace',
    'crayon',
    'digest',
    'evaluate',
    'glue',
    'gtable',
    'isoband',
    'jsonlite',
    'labeling',
    'mime',
    'pkgconfig',
    'ps',
    'remotes',
    'rlang',
    'stringi',
    'systemfonts',
    'withr',
    'xfun',
    'RInside',
    'RProtoBuf',
    'cli',
    'desc',
    'diffobj',
    'ellipsis',
    'htmltools',
    'lifecycle',
    'markdown',
    'munsell',
    'processx',
    'stringr',
    'textshaping',
    'tinytex',
    'callr',
    'knitr',
    'ragg',
    'scales',
    'vctrs',
    'pillar',
    'pkgbuild',
    'rmarkdown',
    'pkgload',
    'tibble',
    'ggplot2',
    'rematch2',
    'waldo',
    'testthat',
]);

const R405jmv = R405base.concat([
    'GPArotation',
    'RcppParallel',
    'backports',
    'ca',
    'carData',
    'contfrac',
    'glasso',
    'jpeg',
    'lisrelToR',
    'matrixStats',
    'matrixcalc',
    'nloptr',
    'numDeriv',
    'pbivnorm',
    'png',
    'qvcalc',
    'rematch',
    'tmvnsim',
    'truncnorm',
    'zip',
    'Formula',
    'MatrixModels',
    'PMCMR',
    'RUnit',
    'RcppArmadillo',
    'RcppEigen',
    'Rsolnp',
    'SparseM',
    'TH.data',
    'XML',
    'abind',
    'caTools',
    'cellranger',
    'checkmate',
    'clipr',
    'coda',
    'corpcor',
    'data.table',
    'deSolve',
    'elliptic',
    'estimability',
    'fdrtool',
    'forcats',
    'generics',
    'gridExtra',
    'gtools',
    'hms',
    'htmlwidgets',
    'igraph',
    'latticeExtra',
    'minqa',
    'mnormt',
    'mvnormtest',
    'mvtnorm',
    'openxlsx',
    'pbapply',
    'plyr',
    'purrr',
    'relimp',
    'sp',
    'ssanv',
    'statmod',
    'xtable',
    'zoo',
    'StanHeaders',
    'conquer',
    'emmeans',
    'exactci',
    'ggridges',
    'gnm',
    'gplots',
    'htmlTable',
    'hypergeo',
    'kutils',
    'lavaan',
    'lme4',
    'lmtest',
    'maptools',
    'progress',
    'psych',
    'readr',
    'reshape',
    'reshape2',
    'rpf',
    'sandwich',
    'tidyselect',
    'viridis',
    'BayesFactor',
    'Hmisc',
    'OpenMx',
    'ROCR',
    'dplyr',
    'exact2x2',
    'haven',
    'lmerTest',
    'multcomp',
    'quantreg',
    'readxl',
    'regsem',
    'rockchalk',
    'vcd',
    'arm',
    'qgraph',
    'rio',
    'tidyr',
    'vcdExtra',
    'GGally',
    'broom',
    'mi',
    'pbkrtest',
    'sem',
    'car',
    'semPlot',
    'afex',
]);

const R412base = included.concat([
    'jmvcore',
    'R6', 'RColorBrewer', 'base64enc', 'brio', 'cpp11', 'curl', 'farver', 'fastmap', 'magrittr', 'praise',
    'rprojroot', 'rstudioapi', 'utf8', 'viridisLite', 'yaml', 'Rcpp', 'colorspace', 'crayon', 'digest',
    'evaluate', 'fansi', 'glue', 'gtable', 'isoband', 'jsonlite', 'labeling', 'pkgconfig', 'ps', 'remotes', 'rlang',
    'stringi', 'systemfonts', 'withr', 'xfun', 'RInside', 'RProtoBuf', 'cli', 'desc', 'diffobj', 'ellipsis',
    'highr', 'htmltools', 'lifecycle', 'munsell', 'processx', 'stringr', 'textshaping', 'tinytex', 'callr',
    'jquerylib', 'knitr', 'pkgload', 'ragg', 'scales', 'vctrs', 'pillar', 'rmarkdown', 'tibble', 'ggplot2',
    'rematch2', 'waldo', 'testthat'
]);

const R412jmv = R412base.concat([
    'BH', 'GPArotation', 'RcppParallel', 'SQUAREM', 'backports', 'bitops', 'ca',
    'carData', 'contfrac', 'glasso', 'gower', 'jpeg', 'lisrelToR', 'listenv',
    'matrixStats', 'nloptr', 'numDeriv', 'pbivnorm', 'png', 'prettyunits', 'qvcalc',
    'tmvnsim', 'truncnorm', 'zip', 'Formula', 'MatrixModels', 'PMCMR', 'RUnit',
    'RcppArmadillo', 'RcppEigen', 'Rsolnp', 'SparseM', 'TH.data', 'XML', 'abind',
    'caTools', 'checkmate', 'coda', 'corpcor', 'data.table', 'deSolve', 'elliptic',
    'estimability', 'fdrtool', 'forcats', 'generics', 'globals', 'gridExtra',
    'gtools', 'hms', 'htmlwidgets', 'igraph', 'iterators', 'latticeExtra', 'minqa',
    'mnormt', 'mvnormtest', 'mvtnorm', 'openxlsx', 'parallelly', 'pbapply', 'plyr',
    'progressr', 'proxy', 'purrr', 'relimp', 'sp', 'ssanv', 'timeDate', 'xtable',
    'zoo', 'ModelMetrics', 'StanHeaders', 'e1071', 'emmeans', 'exactci', 'foreach',
    'future', 'ggridges', 'gnm', 'gplots', 'htmlTable', 'hypergeo', 'kutils',
    'lavaan', 'lme4', 'lmtest', 'lubridate', 'maptools', 'pROC', 'progress',
    'psych', 'reshape', 'reshape2', 'rpf', 'sandwich', 'tidyselect', 'viridis',
    'BayesFactor', 'Hmisc', 'OpenMx', 'ROCR', 'arm', 'dplyr', 'exact2x2',
    'future.apply', 'lmerTest', 'multcomp', 'regsem', 'rockchalk', 'vcd', 'lava',
    'mi', 'qgraph', 'tidyr', 'vcdExtra', 'GGally', 'broom', 'prodlim', 'sem',
    'ipred', 'pbkrtest', 'semPlot', 'recipes', 'caret', 'conquer', 'quantreg',
    'car', 'afex'
]);

const R413base = included.concat([
    'jmvcore',
    'R6', 'RColorBrewer', 'base64enc', 'brio', 'cpp11', 'curl', 'farver', 'fastmap',
    'magrittr', 'praise', 'rappdirs', 'rprojroot', 'utf8', 'viridisLite', 'yaml',
    'Rcpp', 'cli', 'colorspace', 'crayon', 'digest', 'evaluate', 'fansi', 'fs',
    'glue', 'isoband', 'jsonlite', 'labeling', 'mime', 'pkgconfig', 'ps', 'remotes',
    'rlang', 'stringi', 'systemfonts', 'withr', 'xfun', 'RInside', 'RProtoBuf',
    'cachem', 'desc', 'diffobj', 'ellipsis', 'highr', 'lifecycle', 'munsell',
    'processx', 'textshaping', 'tinytex', 'callr', 'gtable', 'htmltools', 'knitr',
    'memoise', 'pkgload', 'ragg', 'scales', 'vctrs', 'fontawesome', 'jquerylib',
    'pillar', 'sass', 'stringr', 'bslib', 'tibble', 'ggplot2', 'rematch2',
    'rmarkdown', 'waldo', 'testthat',
]);

const R413jmv = R413base.concat([
    'BH', 'RcppParallel', 'backports', 'bitops', 'ca', 'carData', 'contfrac',
    'glasso', 'jpeg', 'lisrelToR', 'mnormt', 'numDeriv', 'pbivnorm', 'png',
    'prettyunits', 'quadprog', 'qvcalc', 'rematch', 'rstudioapi', 'zip', 'Formula',
    'GPArotation', 'MatrixModels', 'PMCMR', 'RUnit', 'RcppEigen', 'SparseM',
    'TH.data', 'XML', 'abind', 'caTools', 'cellranger', 'checkmate', 'coda',
    'corpcor', 'data.table', 'deSolve', 'elliptic', 'estimability', 'fdrtool',
    'forcats', 'generics', 'ggrepel', 'ggridges', 'gridExtra', 'gtools', 'here',
    'hms', 'htmlwidgets', 'igraph', 'lavaan', 'minqa', 'mvnormtest', 'mvtnorm',
    'nloptr', 'openxlsx', 'pbapply', 'plyr', 'psych', 'purrr', 'relimp', 'ssanv',
    'tidyselect', 'xtable', 'zoo', 'StanHeaders', 'dplyr', 'emmeans', 'exactci',
    'gnm', 'gplots', 'htmlTable', 'hypergeo', 'kutils', 'lme4', 'lmtest',
    'progress', 'quantreg', 'reshape', 'reshape2', 'rpf', 'sandwich', 'viridis',
    'BayesFactor', 'Hmisc', 'OpenMx', 'ROCR', 'arm', 'exact2x2', 'lmerTest',
    'multcomp', 'readxl', 'rockchalk', 'tidyr', 'vcd', 'GGally', 'broom', 'mi',
    'qgraph', 'vcdExtra', 'pbkrtest', 'sem', 'car', 'semPlot', 'afex',
]);

const R432base = included.concat([
    'jmvcore',
    'R6', 'RColorBrewer', 'base64enc', 'brio', 'cpp11', 'curl', 'farver', 'fastmap',
    'magrittr', 'praise', 'rappdirs', 'rprojroot', 'utf8', 'viridisLite', 'yaml',
    'Matrix', 'Rcpp', 'cli', 'colorspace', 'crayon', 'digest', 'evaluate', 'fansi',
    'fs', 'glue', 'isoband', 'jsonlite', 'labeling', 'mime', 'pkgconfig', 'ps',
    'remotes', 'rlang', 'stringi', 'systemfonts', 'withr', 'xfun', 'RInside',
    'RProtoBuf', 'cachem', 'desc', 'diffobj', 'ellipsis', 'highr', 'lifecycle',
    'munsell', 'processx', 'textshaping', 'tinytex', 'callr', 'gtable', 'htmltools',
    'knitr', 'memoise', 'ragg', 'scales', 'vctrs', 'fontawesome', 'jquerylib',
    'pillar', 'pkgbuild', 'sass', 'stringr', 'bslib', 'pkgload', 'tibble', 'ggplot2',
    'rematch2', 'rmarkdown', 'waldo', 'testthat',
]);

const R432jmv = R432base.concat([
    'BH', 'RcppParallel', 'backports', 'bit', 'bitops', 'ca', 'carData',
    'contfrac', 'glasso', 'jpeg', 'lisrelToR', 'mnormt', 'numDeriv', 'pbivnorm',
    'png', 'prettyunits', 'quadprog', 'qvcalc', 'rematch', 'rstudioapi', 'zip',
    'Formula', 'GPArotation', 'MatrixModels', 'PMCMR', 'RUnit', 'RcppEigen',
    'SparseM', 'TH.data', 'XML', 'abind', 'bit64', 'caTools', 'cellranger',
    'checkmate', 'clipr', 'coda', 'corpcor', 'data.table', 'deSolve', 'elliptic',
    'estimability', 'fdrtool', 'forcats', 'generics', 'ggrepel', 'ggridges',
    'gridExtra', 'gtools', 'here', 'hms', 'htmlwidgets', 'igraph', 'lavaan',
    'minqa', 'mvnormtest', 'mvtnorm', 'nloptr', 'openxlsx', 'patchwork', 'pbapply',
    'plyr', 'psych', 'purrr', 'relimp', 'ssanv', 'tidyselect', 'tzdb', 'xtable',
    'zoo', 'StanHeaders', 'dplyr', 'emmeans', 'exactci', 'gnm', 'gplots',
    'htmlTable', 'hypergeo', 'kutils', 'lme4', 'lmtest', 'progress', 'quantreg',
    'reshape2', 'rpf', 'sandwich', 'viridis', 'BayesFactor', 'Hmisc', 'OpenMx',
    'ROCR', 'arm', 'exact2x2', 'lmerTest', 'multcomp', 'readxl', 'rockchalk',
    'tidyr', 'vcd', 'vroom', 'broom', 'mi', 'qgraph', 'readr', 'vcdExtra', 'haven',
    'pbkrtest', 'sem', 'car', 'labelled', 'semPlot', 'afex', 'broom.helpers',
    'ggstats', 'GGally',
]);

const R441base = included.concat([
    'jmvcore',
    'R6', 'RColorBrewer', 'base64enc', 'brio', 'cpp11', 'curl', 'farver', 'fastmap',
    'magrittr', 'praise', 'rappdirs', 'rprojroot', 'utf8', 'viridisLite', 'yaml',
    'Matrix', 'Rcpp', 'cli', 'colorspace', 'crayon', 'digest', 'evaluate', 'fansi',
    'fs', 'glue', 'isoband', 'jsonlite', 'labeling', 'mime', 'pkgconfig', 'ps',
    'remotes', 'rlang', 'withr', 'xfun', 'RInside', 'RProtoBuf', 'cachem', 'desc',
    'diffobj', 'highr', 'htmltools', 'lifecycle', 'munsell', 'processx', 'tinytex',
    'callr', 'fontawesome', 'gtable', 'jquerylib', 'knitr', 'memoise', 'sass',
    'scales', 'systemfonts', 'vctrs', 'bslib', 'pillar', 'pkgbuild', 'textshaping',
    'pkgload', 'ragg', 'rmarkdown', 'tibble', 'ggplot2', 'rematch2', 'waldo',
    'testthat'
]);

const R441jmv = R441base.concat([
    'BH', 'RcppParallel', 'backports', 'bit', 'bitops', 'ca', 'carData', 'contfrac',
    'glasso', 'jpeg', 'lisrelToR', 'mnormt', 'nloptr', 'numDeriv', 'pbivnorm',
    'png', 'prettyunits', 'quadprog', 'qvcalc', 'rematch', 'rstudioapi', 'zip',
    'Deriv', 'Formula', 'GPArotation', 'MatrixModels', 'PMCMR', 'RUnit',
    'RcppEigen', 'SparseM', 'TH.data', 'XML', 'abind', 'bit64', 'caTools',
    'cellranger', 'checkmate', 'clipr', 'coda', 'corpcor', 'cowplot', 'data.table',
    'deSolve', 'elliptic', 'estimability', 'fdrtool', 'forcats', 'generics',
    'ggrepel', 'ggridges', 'gridExtra', 'gtools', 'here', 'hms', 'htmlwidgets',
    'igraph', 'lavaan', 'microbenchmark', 'minqa', 'mvnormtest', 'mvtnorm',
    'patchwork', 'pbapply', 'plyr', 'purrr', 'relimp', 'ssanv', 'stringi',
    'tidyselect', 'tzdb', 'xtable', 'zoo', 'StanHeaders', 'dplyr', 'emmeans',
    'exactci', 'gnm', 'gplots', 'hypergeo', 'lme4', 'lmtest', 'openxlsx',
    'progress', 'psych', 'quantreg', 'rpf', 'sandwich', 'stringr', 'viridis',
    'BayesFactor', 'OpenMx', 'ROCR', 'arm', 'exact2x2', 'htmlTable', 'kutils',
    'lmerTest', 'multcomp', 'readxl', 'reshape2', 'tidyr', 'vcd', 'vroom', 'Hmisc',
    'broom', 'mi', 'readr', 'rockchalk', 'vcdExtra', 'haven', 'modelr', 'qgraph',
    'sem', 'doBy', 'labelled', 'semPlot', 'broom.helpers', 'pbkrtest', 'car',
    'ggstats', 'GGally', 'afex'
]);

const R450base = included.concat([
    'jmvcore',
    'R6', 'RColorBrewer', 'backports', 'base64enc', 'brio', 'cpp11', 'curl',
    'devEMF', 'evaluate', 'farver', 'fastmap', 'fontBitstreamVera',
    'fontLiberation', 'magrittr', 'praise', 'rappdirs', 'rprojroot', 'sys', 'utf8',
    'uuid', 'viridisLite', 'yaml', 'zip', 'Rcpp', 'askpass', 'cli', 'crayon',
    'data.table', 'digest', 'fansi', 'fontquiver', 'fs', 'generics', 'glue',
    'isoband', 'jsonlite', 'labeling', 'mime', 'pkgconfig', 'ps', 'remotes',
    'rlang', 'stargazer', 'stringi', 'withr', 'xfun', 'xtable', 'RInside',
    'RProtoBuf', 'cachem', 'desc', 'diffobj', 'highr', 'htmltools', 'lifecycle',
    'openssl', 'openxlsx', 'processx', 'tinytex', 'xml2', 'callr', 'fontawesome',
    'gtable', 'jquerylib', 'knitr', 'memoise', 'sass', 'scales', 'systemfonts',
    'vctrs', 'waldo', 'bslib', 'gdtools', 'pillar', 'pkgbuild', 'purrr', 'stringr',
    'textshaping', 'tidyselect', 'pkgload', 'ragg', 'rmarkdown', 'tibble', 'dplyr',
    'ggplot2', 'officer', 'testthat', 'flextable', 'rvg', 'tidyr', 'broom', 'export'
]);

const R450jmv = R450base.concat([
    'BH', 'RcppParallel', 'bitops', 'ca', 'carData', 'contfrac', 'glasso', 'jpeg',
    'lisrelToR', 'matrixStats', 'mnormt', 'nloptr', 'numDeriv', 'pbivnorm', 'png',
    'prettyunits', 'quadprog', 'qvcalc', 'rematch', 'rstudioapi', 'Deriv',
    'Formula', 'GPArotation', 'Matrix', 'PMCMR', 'RUnit', 'RcppEigen', 'SparseM',
    'TH.data', 'XML', 'abind', 'caTools', 'cellranger', 'checkmate', 'coda',
    'colorspace', 'corpcor', 'cowplot', 'deSolve', 'elliptic', 'estimability',
    'fdrtool', 'forcats', 'ggrepel', 'ggridges', 'gridExtra', 'gtools', 'here',
    'hms', 'htmlwidgets', 'lavaan', 'microbenchmark', 'minqa', 'modelr',
    'mvnormtest', 'mvtnorm', 'patchwork', 'pbapply', 'plyr', 'rbibutils', 'relimp',
    'ssanv', 'zoo', 'MatrixModels', 'Rdpack', 'StanHeaders', 'doBy', 'emmeans',
    'exactci', 'ggstats', 'gnm', 'gplots', 'htmlTable', 'hypergeo', 'igraph',
    'kutils', 'lmtest', 'progress', 'psych', 'reshape2', 'rpf', 'sandwich',
    'viridis', 'BayesFactor', 'GGally', 'Hmisc', 'OpenMx', 'ROCR', 'exact2x2',
    'multcomp', 'quantreg', 'readxl', 'reformulas', 'vcd', 'lme4', 'qgraph',
    'vcdExtra', 'arm', 'lmerTest', 'pbkrtest', 'rockchalk', 'car', 'mi', 'afex',
    'sem', 'semPlot'
]);

module.exports = {
    '4.0.2': {
        mran_url: 'https://packagemanager.posit.co/cran/2020-08-24',
        base_packages: R402base,
        jmv_packages: R402jmv,
    },
    '4.0.5': {
        mran_url: 'https://packagemanager.posit.co/cran/2021-04-01',
        base_packages: R405base,
        jmv_packages: R405jmv,
    },
    '4.1.1': {  // same as 405 (as you can see)
        mran_url: 'https://packagemanager.posit.co/cran/2021-04-01',
        base_packages: R405base,
        jmv_packages: R405jmv,
    },
    '4.1.2': {
        mran_url: 'https://packagemanager.posit.co/cran/2021-12-29',
        base_packages: R412base,
        jmv_packages: R412jmv,
    },
    '4.1.3': {
        mran_url: ['https://repo.jamovi.org/cran-linux/2023-04-07,https://packagemanager.posit.co/cran/2023-04-07', 'https://repo.jamovi.org/cran/2023-04-07,https://packagemanager.posit.co/cran/2023-04-07', 'https://repo.jamovi.org/cran/2023-04-07,https://packagemanager.posit.co/cran/2023-04-07'][['linux', 'darwin', 'win32'].indexOf(process.platform)],
        base_packages: R413base,
        jmv_packages: R413jmv,
    },
    '4.3.2': {
        mran_url: [undefined, 'https://packagemanager.posit.co/cran/2024-01-09,https://repo.jamovi.org/cran/2024-01-09', 'https://packagemanager.posit.co/cran/2024-01-09,https://repo.jamovi.org/cran/2024-01-09'][['linux', 'darwin', 'win32'].indexOf(process.platform)],
        arch_urls : (process.platform !== 'linux' ? undefined : {
            arm64: 'https://repo.jamovi.org/cran-linux/2024-01-09/arm64,https://packagemanager.posit.co/cran/2024-01-09',
            x64:   'https://repo.jamovi.org/cran-linux/2024-01-09/x64,https://packagemanager.posit.co/cran/2024-01-09',
        }),
        base_packages: R432base,
        jmv_packages: R432jmv,
    },
    '4.4.1': {
        mran_url: (process.platform === 'linux' ? undefined : 'https://packagemanager.posit.co/cran/2024-08-07,https://repo.jamovi.org/cran/2024-08-07'),
        arch_urls : (process.platform !== 'linux' ? undefined : {
            arm64: 'https://repo.jamovi.org/cran-linux/2024-08-07/arm64,https://packagemanager.posit.co/cran/2024-08-07',
            x64:   'https://repo.jamovi.org/cran-linux/2024-08-07/x64,https://packagemanager.posit.co/cran/2024-08-07',
        }),
        base_packages: R441base,
        jmv_packages: R441jmv,
    },
    '4.5.0': {
        mran_url: (process.platform === 'linux' ? undefined : 'https://repo.jamovi.org/cran/2025-05-25,https://packagemanager.posit.co/cran/2025-05-25'),
        arch_urls : (process.platform !== 'linux' ? undefined : {
            arm64: 'https://repo.jamovi.org/cran-linux/2025-05-25/arm64,https://packagemanager.posit.co/cran/2025-05-25',
            x64:   'https://repo.jamovi.org/cran-linux/2025-05-25/x64,https://packagemanager.posit.co/cran/2025-05-25',
        }),
        base_packages: R450base,
        jmv_packages: R450jmv,
    },
};
